
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const HIDE_AUTH_MESSAGES = 'HIDE_AUTH_MESSAGES'

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const SET_FILTER_LIMIT = 'SET_FILTER_LIMIT'
export const SET_FILTER_DONE = 'SET_FILTER_DONE'
export const SET_FILTER_TITLE = 'SET_FILTER_TITLE'

export const LOGOUT = 'LOGOUT'
